version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production